### ISSUE TITLE
Type conflict between InstantClasses  ==> TInstantStreamFormat & FireDAC.Stan.Intf ==> TFDStorageFormat

### ISSUE THREAD

**Issue by mderie** [EtheaDev/InstantObjects#4]
In InstantFireDAC

  case BlobStreamFormat of
    sfBinary: Result := Result + 'BlobStreamFormat=sfBinary'+sLineBreak;
    sfXML: Result := Result + 'BlobStreamFormat=sfXML'+sLineBreak;
    sfJSON: Result := Result + 'BlobStreamFormat=sfJSON'+sLineBreak;
  end;

==> The three possible values exist in two different enumerations.
I know Delphi lacks of namespace support...

BTW : why a conditional define ?

  TInstantStreamFormat = (
    sfBinary
    , sfXML
    {$IFDEF DELPHI_NEON}
    , sfJSON
    {$ENDIF}
    );

**Comment by carloBarazzetta** [comment]
I've committed a new version that fixes this problem.
The conditiona define is necessary because the default streaming is XML.
If you want to serialize InstantObjects in JSON you need https://github.com/paolo-rossi/delphi-neon and compile with DELPHI_NEON define.
We are working on a REST server demo that uses https://github.com/andrea-magni/MARS server and delphi-neon in the next month.
